In [71]:
%pylab

Using matplotlib backend: TkAgg
Populating the interactive namespace from numpy and matplotlib


In [85]:
import matplotlib.patches as patches

xkcd()

def rotado(vect, ang = np.pi/3):
    rot_matrix = array([[np.cos(ang), -np.sin(ang)], \
                         [np.sin(ang), np.cos(ang)]])
    return np.dot(vect, rot_matrix)

def de_base_tercero(p1, p3):
    vector = p3 - p1
    p2 = rotado(vector)
    return p1 + p2

def p_equilatero(lado, centro = array([0, 0])):
    p2 = array([0, lado / np.sqrt(3)]) + centro
    p1 = rotado(p2 - centro, 2*np.pi/3) + centro
    p3 = rotado(p2 - centro, 4*np.pi/3) + centro
    return array([p1, p2, p3])

def dos_centrales(p1, p2):
    vect = p2 - p1
    return (p1 + 1./3 * vect, p1 + 2./3 * vect)

def sigts_segun(puntos):
    res = np.zeros((4 * len(puntos), 2))
    
    j = 0
    for i in range(0, len(puntos)):
        pi1, pi2 = dos_centrales(puntos[i], puntos[(i + 1) % len(puntos)])
        res[j] = puntos[i]
        res[j + 1] = pi1
        res[j + 2] = de_base_tercero(pi1, pi2)
        res[j + 3] = pi2
        j += 4
    
    return res
        

lado = 1.
i = 1
lims = array([-lado / 2, lado / 2]) * (1 + 1./3) * np.sin(np.pi/3)

set_puntos = []

fig = figure('Snowflake Tabla', figsize = (15, 10), facecolor = 'w')
ax = fig.add_subplot(2,3,1, xlim = lims, ylim = lims)
ax.axis('off')
tx = ax.text(0, 0, str(i), horizontalalignment = 'center', verticalalignment = 'center')

set_puntos.append(p_equilatero(1.))
polig = patches.Polygon(set_puntos[0], fill = False, color = 'b')
ax.add_patch(polig)

for i in range(2, 7):
    ax = fig.add_subplot(2,3,i, xlim = lims, ylim = lims)
    ax.axis('off')
    tx = ax.text(0, 0, str(i), horizontalalignment = 'center', verticalalignment = 'center')
    
    puntos = sigts_segun(set_puntos[-1])
    set_puntos.append(puntos)
    
    polig = patches.Polygon(puntos, fill = False, color = 'b')
    ax.add_patch(polig)

plt.show()

In [ ]:
import matplotlib.animation as animation

framesps = 1
segundos = 6



In [13]:
def dist(p1, p2):
    return np.sqrt((p1 - p2)[0]**2 + (p1 - p2)[1]**2)

equil = p_equilatero(1.)
dist(equil[0], equil[2])

1.0

In [15]:
del ax.patches[0]

In [29]:
print equil
print np.append(equil, [[0,0]], axis = 0)


[[ 0.5        -0.28867513]
 [ 0.          0.57735027]
 [-0.5        -0.28867513]]
[[ 0.5        -0.28867513]
 [ 0.          0.57735027]
 [-0.5        -0.28867513]
 [ 0.          0.        ]]


In [61]:
pi1, pi2 = dos_centrales(equil[0], equil[1])
print pi1
print equil
print sigts_segun(equil)
print sigts_segun(sigts_segun(equil))

[  3.33333333e-01   5.55111512e-17]
[[ 0.5        -0.28867513]
 [ 0.          0.57735027]
 [-0.5        -0.28867513]]
[[  5.00000000e-01  -2.88675135e-01]
 [  3.33333333e-01   5.55111512e-17]
 [  1.66666667e-01   2.88675135e-01]
 [  0.00000000e+00   5.77350269e-01]
 [ -1.66666667e-01   2.88675135e-01]
 [ -3.33333333e-01  -1.11022302e-16]
 [ -5.00000000e-01  -2.88675135e-01]
 [ -1.66666667e-01  -2.88675135e-01]
 [  1.66666667e-01  -2.88675135e-01]]
[[  5.00000000e-01  -2.88675135e-01]
 [  4.44444444e-01  -1.92450090e-01]
 [  3.88888889e-01  -9.62250449e-02]
 [  3.33333333e-01   5.55111512e-17]
 [  2.77777778e-01   9.62250449e-02]
 [  2.22222222e-01   1.92450090e-01]
 [  1.66666667e-01   2.88675135e-01]
 [  1.11111111e-01   3.84900179e-01]
 [  5.55555556e-02   4.81125224e-01]
 [  0.00000000e+00   5.77350269e-01]
 [ -5.55555556e-02   4.81125224e-01]
 [ -1.11111111e-01   3.84900179e-01]
 [ -1.66666667e-01   2.88675135e-01]
 [ -2.22222222e-01   1.92450090e-01]
 [ -2.77777778e-01   9.6225044